import 'dart:math';
import 'utils.dart';
import 'options.dart';

var utils = new Utils();
var options = new Options();
var humans = [];
var families = [];
var hobbies = [];
var populationPyramide = [];
var rnd = new Random();
var covid = [];
int familyCounter = 0;
int chance = 0;
int yetiskinMin = 13900;
int yetiskinMax = 24699;
int cocukMin = 24700;
int cocukMax = 99999;
int yasliMin = 0;
int yasliMax = 13899;
